/*
 * This file is part of the @gnss/nmea distribution (https://github.com/node-ntrip/nmea).
 * Copyright (c) 2020 Nebojsa Cvetkovic.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

export enum NmeaSentenceType {
    AAM = 'AAM',
    ACK = 'ACK',
    ADS = 'ADS',
    AKD = 'AKD',
    ALA = 'ALA',
    ALM = 'ALM',
    ALR = 'ALR',
    APB = 'APB',
    BEC = 'BEC',
    BOD = 'BOD',
    BWC = 'BWC',
    BWR = 'BWR',
    BWW = 'BWW',
    CEK = 'CEK',
    COP = 'COP',
    CUR = 'CUR',
    DBT = 'DBT',
    DCN = 'DCN',
    DCR = 'DCR',
    DDC = 'DDC',
    DOR = 'DOR',
    DPT = 'DPT',
    DSC = 'DSC',
    DSE = 'DSE',
    DSI = 'DSI',
    DSR = 'DSR',
    DTM = 'DTM',
    ETL = 'ETL',
    EVE = 'EVE',
    FIR = 'FIR',
    FSI = 'FSI',
    GBS = 'GBS',
    GEN = 'GEN',
    GFA = 'GFA',
    GGA = 'GGA',
    GLC = 'GLC',
    GLL = 'GLL',
    GMP = 'GMP',
    GNS = 'GNS',
    GRS = 'GRS',
    GSA = 'GSA',
    GST = 'GST',
    GSV = 'GSV',
    HBT = 'HBT',
    HDG = 'HDG',
    HDT = 'HDT',
    HMR = 'HMR',
    HMS = 'HMS',
    HSC = 'HSC',
    HSS = 'HSS',
    HTC = 'HTC',
    HTD = 'HTD',
    LCD = 'LCD',
    MLA = 'MLA',
    MSK = 'MSK',
    MSS = 'MSS',
    MTW = 'MTW',
    MWD = 'MWD',
    MWV = 'MWV',
    NAK = 'NAK',
    NRM = 'NRM',
    NRX = 'NRX',
    OSD = 'OSD',
    POS = 'POS',
    PRC = 'PRC',
    RMA = 'RMA',
    RMB = 'RMB',
    RMC = 'RMC',
    ROR = 'ROR',
    ROT = 'ROT',
    RPM = 'RPM',
    RSA = 'RSA',
    RSD = 'RSD',
    RST = 'RST',
    RTE = 'RTE',
    SFI = 'SFI',
    SID = 'SID',
    STN = 'STN',
    THS = 'THS',
    TLB = 'TLB',
    TLL = 'TLL',
    TRC = 'TRC',
    TRD = 'TRD',
    TTM = 'TTM',
    TUT = 'TUT',
    TXT = 'TXT',
    UID = 'UID',
    VBW = 'VBW',
    VDR = 'VDR',
    VER = 'VER',
    VHW = 'VHW',
    VLW = 'VLW',
    VPW = 'VPW',
    VTG = 'VTG',
    WAT = 'WAT',
    WCV = 'WCV',
    WNC = 'WNC',
    WPL = 'WPL',
    XDR = 'XDR',
    XTE = 'XTE',
    XTR = 'XTR',
    ZDA = 'ZDA',
    ZDL = 'ZDL',
    ZFO = 'ZFO',
    ZTG = 'ZTG'
}
